
var UserConstants = {
  RECEIVE_USERS: "RECEIVE_USERS",
  RECEIVE_USER: "RECEIVE_USER",
  RECEIVE_PHOTO: "RECEIVE_PHOTO",
  FRIEND_RECEIVED: "FRIEND_RECEIVED",
  FRIENDS_RECEIVED: "FRIENDS_RECEIVED",
  FRIEND_REMOVED: "FRIEND_REMOVED"
};

module.exports = UserConstants;
